recipe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from recipeapp.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('recipes/', include('recipeapp.urls')),
    path('users/', include('usersapp.urls', namespace='usersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersapp/urls.py
from django.urls import path
from . import views


app_name = 'usersapp'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),

]

usersapp/models.py
from django.db import models

# Create your models here.

usersapp/forms.py
from django import forms
from django.contrib.auth import get_user_model


class LoginUserForm(forms.Form):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

    widgets = {
        'email': forms.TextInput(attrs={'class': 'form-input'}),
        'first_name': forms.TextInput(attrs={'class': 'form-input'}),
        'last_name': forms.TextInput(attrs={'class': 'form-input'}),
    }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким E-mail уже существует')
        return email

usersapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import LoginUserForm, RegisterForm
from recipeapp.models import Category


def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'],
                                password=cd['password'])
            if user and user.is_active:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return HttpResponseRedirect(reverse('index'))
    else:
        form = LoginUserForm()
        categories = Category.objects.all()
    return render(request, 'usersapp/login.html', {'form': form, 'categories': categories})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('usersapp:login'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect('index')
    else:
        form = RegisterForm()
        categories = Category.objects.all()
    return render(request, 'usersapp/register.html', {'form': form, 'categories': categories})

usersapp/templates/usersapp/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'usersapp/css/login_register.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="center-from">
    <div class="login-card">
        <h2>Авторизация</h2>

        <form class="login-card-items" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>

            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}

            <strong><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label></strong>
            <p>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>

            {% endfor %}
            <p class="button-item">
                    <button class="button" type="submit">Войти</button>
            </p>
        </form>
        <a href="{% url 'usersapp:register' %}"><button class="button" type="submit">Регистрация</button></a>
    </div>
</div>
{% endblock %}

usersapp/templates/usersapp/register.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link href="{% static 'usersapp/css/login_register.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="center-from">
    <div class="login-card">
        <h2>Регистрация</h2>

        <form class="login-card-items" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>

            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}

            <strong><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label></strong>
            <p>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>

            {% endfor %}
            <p class="button">
                <button class="button" type="submit">Зарегистрироваться</button>
            </p>
        </form>
    </div>
</div>
{% endblock%}