recipe_website/urls.py
from django.contrib import admin
from django.urls import path, include
from recipeapp.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('recipes/', include('recipeapp.urls')),
    path('users/', include('usersapp.urls', namespace='usersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersapp/urls.py
from django.urls import path
from . import views


app_name = 'usersapp'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
{% block style %}
{% endblock %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Сайт{% endblock %}</title>


    <link rel="stylesheet" href="{% static 'recipeapp/css/base.css' %}">

</head>
<body>
    <div class="header">
        <header class="center header-items">
            <a class="header_link" href="{% url 'index' %}">
                <div class="header-items-left">
                    <img class="header_icons_left" src="{% static 'recipeapp/images/cooking.svg' %}" alt="cooking">
                    <p class="title">Кушайте много Кушайте вкусно</p>
                </div>
                </a>
            <div class="header-items-center">
            <a class="header_link" href= "{% url 'all_recipes' %}">Показать все рецепты</a>
            <a class="header_link" href= "{% url 'add_recipe' %}">Добавить рецепт</a>
            <a class="header_link" href= "{% url 'search_recipes' %}">Найти рецепт</a>
            <nav class="dws-menu"> <!-- menu-button -->
                <p class="header_link">Категории ▼</p>
                <div class="menu">


                        <div>
                            <div class="menu-items">
                                {% for category in categories %}
                                <p><a  class="text_menu" href="{% url 'recipes_by_categories' category_id=category.pk %}">{{ category.title }}</a></p>
                                {% endfor %}
                            </div>
                        </div>
                </div>
            </nav>
            </div>


            <div class="header-items-right text-items-right">
            {% if user.is_authenticated %}
                {{ user.username }}  <a href="{% url 'usersapp:logout' %}">
                    <img class="header_icons_rigth" src="{% static 'recipeapp/images/logout.svg' %}" alt="logout">
                </a>
            {% else %}
                <a href="{% url 'usersapp:login' %}"><img class="header_icons_rigth" src="{% static 'recipeapp/images/login.svg' %}" alt="login"></a>
            {% endif %}
            </div>
        </header>
    </div>

    <div class="content">
    {% block content %}
        <p>Скоро тут появится текст...</p>
    {% endblock %}
    </div>
    <div class="footer">
        <div class="center footer_items">
            <p>2024 © developed by Vatsek Pavel</p>
            <div class="footer-contacts">
                <a href="https://wa.me/9265974869" target="_blank"><img class="footer-icons" src="{% static 'recipeapp/images/whatsapp.png' %}" alt="whatsapp"></a>
                <a href="https://t.me/+79265974869" target="_blank"><img class="footer-icons" src="{% static 'recipeapp/images/telegram.png' %}" alt="telegram"></a>
             </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

</body>
</html>